### ISSUE TITLE
node not found? osmium complains about invalid_location

### ISSUE THREAD

**Issue by tobwen** [joto/osm-history-splitter#1] opened 2016-03-16 07:37 UTC
I've just successfully built https://github.com/joto/osm-history-splitter/commit/e13f53b7e5f33e9efe2ab68a581f5e483cc656ee

My splitter config is the one from the wiki: `woerrstadt.osh.pbf    BBOX    8.1010,49.8303,8.1359,49.8567`
The history extract is germany.osm.hbf downloaded from Peter.

I'm getting this error immediately after starting the splitter:

> terminate called after throwing an instance of 'osmium::invalid_location'

Anyone with an idea, what's wrong here?
I'm on Debian Jessy, 64-bit.

**Comment by joto** [comment] 2016-06-13 16:27
The file is missing a node needed for some way or relation so it can't determine the location.

**Comment by kcwu** [comment] 2016-06-14 02:40
Do you mean the planet history generated in http://planet.osm.org/pbf/full-history/ is broken?

**Comment by tobwen** [comment] 2016-06-14 04:27
@joto Please don't close a discussion, while a problem isn't solved or users are still in discussion.

I think, the port of the history-splitter simply should ignore the missing node, f.e. give a warning and move on.

**Comment by joto** [comment] 2016-06-14 07:02
@kcwu No. The original question was about reading a germany extract not the planet.

@tobwen Sorry, please try again with current splitter and current libosmium and see whether the problem is still there. There are several changes in both and this might be fixed by now.

**Comment by kcwu** [comment] 2016-06-14 07:22
FYI, I encountered the same issue with the official full planet history dump, either history-160502.osm.pbf or history-160516.osm.pbf. I forgot which one.

I will try again when I have free time.

**Comment by kcwu** [comment] 2016-12-25 11:34
Sorry for late update.
I tried latest revision https://github.com/joto/osm-history-splitter/commit/5e5ceb839615e89c0115b46f54f6a4ef8777d37b with http://planet.osm.org/pbf/full-history/history-161219.osm.pbf
Both softcut and hardcut work well.


```
time ./src/osm-history-splitter ~/history-161219.osm.pbf splitter.config
Peak memory used: 3860 MBytes
real    69m2.448s
user    113m4.020s
sys     45m28.232s
```

```
time ./src/osm-history-splitter --hardcut ~/history-161219.osm.pbf splitter.config
Peak memory used: 2444 MBytes
real    27m8.508s
user    49m31.624s
sys     11m18.728s
```

Tested with http://download.geofabrik.de/asia/taiwan.poly on Google Compute Engine (4vCPU, 4GB ram)

So, I think this issue is already resolved.

**Closed** 2017-01-03 08:52 UTC
